# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration for preparing residual images (specifying all the paths)
# --------------------------------------------------------------------

# General parameters
# number of frames for training, -1 uses all frames
num_frames: -1
# plot images
debug: False
# normalize/scale the difference with corresponding range value
normalize: True
# use the last n frame to calculate the difference image
num_last_n: 8

# input and output folders (Changed by me)
input_base_folder: '/home/vscode/testing/methods/learning-based/MotionSeg3D/data/sequences'
output_base_folder: '/home/vscode/data/kitti/SemanticKITTI/motionseg3d/outputs'
sequence: None # None for all sequences, or a list of numbers
visualize: False

# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 3.0
  fov_down: -25.0
  max_range: 50.0
  min_range: 2.0
